### PR TITLE
JENKINS-34040 Basic support for Pipeline/Workflow plugin

### PR DESCRIPTION
**Pull request by tommysdk**

### CODE REVIEW

**Comment by pskumar448** [comment]
@tommysdk 
Let me know how to contribute to this thread with some features like pagination.

**Comment by tommysdk** [comment]
@pskumar448 that would be much appreciated! The plan now is to get the build to pass and then merge it to master. Then we can improve the experience in small increments with dedicated tickets for each improvement.

**Comment by tommysdk** [comment]
@pskumar448 I've had an issue with jsplumb in pipe.js. It is not working as expected for the workflow/pipeline plugin support (but for traditional views it works). This issue occurred after I merged with master which contained the refactoring you did for dashboard view portlets. I have not yet been able to figure out the cause. My latest commit b3200edcf5a64d950e12740c72748f35fc97941d addressed the issues for both the traditional view as well as the pipeline/workflow plugin view, but it is not using the jsplumb variables as intended. Do you think you could take a look and try to pinpoint the issue? Would be much appreciated.

**Comment by tommysdk** [comment]
Tests in se.diabol.jenkins.pipeline.domain.PipelineTest are taking too long in CI to finish so they fail the build. For me they successfully pass when I run them locally. This needs further troubleshooting.

**Comment by pskumar448** [comment]
@tommysdk 
Figured out the cause for why jsplumb is undefined and in the below PR description explained root cause of the issue.
PR https://github.com/tommysdk/delivery-pipeline-plugin/pull/1

**Comment by tommysdk** [comment]
@pskumar448 thank you very much for your help! Much appreciated!

**Pull request merged**
