### PR TITLE
Exclude job regex

### PR DESCRIPTION
**Pull request by OlgaMaciaszek**

### CODE REVIEW

**Comment by tommysdk** [comment]
@OlgaMaciaszek Thank you! We will have a look and give you some feedback.

**Comment by tommysdk** [comment]
I've gone through the code changes and it looks good in general. I'm a bit concerned with how new features require additions to e.g. the DeliveryPipelineView.getComponent method parameter list, but I think we will need to do some overall refactoring to address such issues.

I haven't tried out the feature yet but I will try to do that in the near future. Will let you know any feedback so we can find a good solution that meets the needs to get this in to master.

**Comment by pskumar448** [comment]
@tommysdk 
Where do can I submit issues related to this PR.

**Comment by rickard-von-essen** [comment]
In general see [how to contribute](https://github.com/Diabol/delivery-pipeline-plugin#how-to-contribute).

If test and find any issues with this PR before it is merge please add you comments here. After it have been merged open a issue according to the instructions above.

**Comment by pskumar448** [comment]
Thanks @rickard-von-essen for the info.

**Comment by pskumar448** [comment]
Issue-1: Arrow is not getting displayed when a job is excluded in pipeline.



Steps to reproduce: 
1. Create a new job called "Build".
2. Create a new job called "PrepareForDeployment".
3. Create a new job called "Deploy".
4. Create a new job called "Test".

5. Edit "Build" job and add "PrepareForDeployment" job as downstream.
6. Edit "PrepareForDeployment" job and add "Deploy" job as downstream.
7. Edit "Deploy" job and add "Test" job as downstream.

8. Create DeliveyPipeline  and name it as "Pipeline"
9. Edit the DeliveryPipeline
    - Add Component and select "Build" job as first job.
    - In "Exclude jobs regular expression" texbox enter "PrepareForDeployment" 

10. Click Ok to save configuration.
       
After removing "PrepareForDeployment" from "Exclude jobs regular expression" textbox, below is pipeline displaying with arrows as expected.

**Comment by pskumar448** [comment]
Issue-2: Pipeline is not displaying properly when the excluded job has multiple downstream jobs



Steps to reproduce:
1. Create a new job called "Build".
2. Create a new job called "UnitTesting".
3. Create a new job called "CodeAnalysis".
4. Create a new job called "Package".
5. Create a new job called "DevDeploy".
6. Create a new job called "DevTestPhase".
7. Create a new job called "DevTestSuite-1".
8. Create a new job called "DevTestSuite-2".
9. Create a new job called "StageDeploy".
10. Create a new job called "StageTestPhase".
11. Create a new job called "StageTestSuite-1".
12. Create a new job called "StageTestSuite-2".

1. Edit "Build" job and add "UnitTesting" job as downstream.
2. Edit "UnitTesting" job and add "CodeAnalysis" job as downstream.
3. Edit "CodeAnalysis" job and add "Package" job as downstream.
4. Edit "Package" job and add "DevDeploy" job as downstream.
5. Edit "DevDeploy" job and add "DevTestPhase" job as downstream.
6. Edit "DevTestPhase" job and add "DevTestSuite-1",  "DevTestSuite-2" and "StageDeploy" as downstreams.
7. Edit "StageDeploy" job and add "StageTestPhase" job as downstream.
8. Edit "StageTestPhase" job and add "StageTestSuite-1" and  "StageTestSuite-2" as downstreams.

1. Create DeliveyPipeline and name it as "Pipeline".
2. Edit the DeliveryPipeline "Pipeline".
    - Add Component and select "Build" job as first job.
    - In "Exclude jobs regular expression" texbox enter "DevTestPhase|StageTestPhase".
3. Click Ok to save configuration.

After removing "DevTestPhase|StageTestPhase" from "Exclude jobs regular expression" textbox, below is pipeline displaying properly as expected.

**Comment by tommysdk** [comment]
@pskumar448 thank you for reviewing this feature request!

The associated JIRA is: https://issues.jenkins-ci.org/browse/JENKINS-26210. This should be prefixed to the commit message according to the contribution guidelines.

**Comment by OlgaMaciaszek** [comment]
Thanks for your comments. Will work on fixes.

**Comment by pskumar448** [comment]
Hi @OlgaMaciaszek 
You can look at my PR #169 which contains the fix for the issues which I have raised. You could look at pipeline/domain/Stage.java file getDownstreamStages() method,  which gives information where to add code to fix. Please fine tune according to the configuration introduced by this feature.

**Comment by OlgaMaciaszek** [comment]
Hello @pskumar448 ,
thanks for your suggestions :). Will do that.

**Comment by OlgaMaciaszek** [comment]
@tommysdk thanks for your quick reply. I will have a look at the issues you have mentioned.

**Comment by OlgaMaciaszek** [comment]
@tommysdk @rickard-von-essen  @pskumar448 
I've fixed the reported bugs. Please have a look and let me know if there is anything else that needs fixing or if we could merge this PR.

**Comment by tommysdk** [comment]
@OlgaMaciaszek Thank you. Can you also rebase with current master as this branch seems to have some conflicts that must be resolved?

**Comment by OlgaMaciaszek** [comment]
Sure; will do it and make another PR

**Comment by OlgaMaciaszek** [comment]
@tommysdk I've resolved the conflicts. Could you have a look?

**Comment by pskumar448** [comment]
Hi @OlgaMaciaszek 
I have verified the 2 issues which I have raised, Issue-1 is fixed and it is rendering as expected.
But still I see Issue-2 persists. Let me know any other details you want to know about Issue-2.

**Comment by pskumar448** [comment]
Issue-3: When given invalid regex expression in "Exclude jobs regular expression" textbox, Pipeline showing error message as "Error communicating to server! Internal Server Error".

Expected: Error message should be appropriate and related to Regex.

Find the error log:
`DevTestPhase|*StageTestPhase*`
`             ^`
`	at java.util.regex.Pattern.error(Pattern.java:1955)`
`	at java.util.regex.Pattern.sequence(Pattern.java:2123)`
`	at java.util.regex.Pattern.expr(Pattern.java:1996)`
`	at java.util.regex.Pattern.compile(Pattern.java:1696)`
`	at java.util.regex.Pattern.<init>(Pattern.java:1351)`
`	at java.util.regex.Pattern.compile(Pattern.java:1028)`
`	at se.diabol.jenkins.pipeline.domain.Stage.extractStages(Stage.java:182)`
`	at se.diabol.jenkins.pipeline.domain.Pipeline.extractPipeline(Pipeline.java:195)`
`	at se.diabol.jenkins.pipeline.DeliveryPipelineView.getComponent(DeliveryPipelineView.java:513)`
`	at se.diabol.jenkins.pipeline.DeliveryPipelineView.getPipelines(DeliveryPipelineView.java:478)`

**Comment by tommysdk** [comment]
@pskumar448 Thank you for helping us review new features! It is much appreciated. Keep at it!

**Comment by OlgaMaciaszek** [comment]
@pskumar448 I will look at it. Are you sure Issue 2 is still there for you? I have been retesting it and it seemed to work fine.

**Comment by OlgaMaciaszek** [comment]
One more issue related to passing parameters between jobs incorrectly has been discovered. I will work on it next week.

**Comment by dstepanov** [comment]
LGTM +1

**Comment by pskumar448** [comment]
Issue4: For the same setup as Issue2, after having builds it is throwing below error and pipeline is showing error.
A small update on the Issue2 setup, please use "Trigger/call builds on other projects" this as build step to invoke "StageTestSuite-1" & "StageTestSuite-2" in "StageTestPhase" job.

`Caused by: java.lang.NullPointerException`
	`at se.diabol.jenkins.pipeline.domain.Pipeline.calculatePipelineRoutes(Pipeline.java:165)`
	`at se.diabol.jenkins.pipeline.domain.Pipeline.calculatePipelineRoutes(Pipeline.java:169)`
	`at se.diabol.jenkins.pipeline.domain.Pipeline.calculatePipelineRoutes(Pipeline.java:169)`
	`at se.diabol.jenkins.pipeline.domain.Pipeline.calculatePipelineRoutes(Pipeline.java:169)`
	`at se.diabol.jenkins.pipeline.domain.Pipeline.calculatePipelineRoutes(Pipeline.java:169)`
	`at se.diabol.jenkins.pipeline.domain.Pipeline.calculatePipelineRoutes(Pipeline.java:169)`
	`at se.diabol.jenkins.pipeline.domain.Pipeline.calculateTotalBuildTime(Pipeline.java:143)`
	`at se.diabol.jenkins.pipeline.domain.Pipeline.createPipelineLatest(Pipeline.java:282)`
	`at se.diabol.jenkins.pipeline.DeliveryPipelineView.getComponent(DeliveryPipelineView.java:521)`
	`at se.diabol.jenkins.pipeline.DeliveryPipelineView.getPipelines(DeliveryPipelineView.java:478)`

**Comment by OlgaMaciaszek** [comment]
Thank you for the thorough tests @pskumar448  :). Will work on fixing this now.

**Comment by OlgaMaciaszek** [comment]
@pskumar448 I have tried to reproduce Issue 2 and Issue 4 following your steps, but I havent' been able to get the exceptions, also after switching "StageTestSuite-1" & "StageTestSuite-2" in "StageTestPhase" to  "Trigger/call builds on other projects". Below, you can find enclosed the screenshots with some details of my config and with the view after applying the regex. Maybe you could send me your xml config files from the jobs history to make sure I'm reproducing it exactly as it should be?

When it comes to the Issue 3, this seems to be a standard way in which DPP handles errors. A 500 HTTP response is passed to pipe.js and this HTTP result is just displayed. The only idea we have regarding changing it would be to parse Java stacktrace in Javascript to display the details, but it does not seem like a great idea; @pskumar448 @tommysdk do you have a better suggestion regarding displaying the error message?

stage-test-phase
dev-test-phase
view
pipeline

**Comment by OlgaMaciaszek** [comment]
@pskumar448 Thank you for providing me test directory with jobs. I have retested on your jobs directory and I still cannot reproduce this bug. Please rebuild the .hpi again from this PR sources and retest. Alternatively, you can use this [hpi](https://drive.google.com/file/d/0B-20tcL_Nhm5UXZYRDFicWF0NXc/view?usp=sharing) which I have built from the PR branch.

**Comment by pskumar448** [comment]
@OlgaMaciaszek 
Could you let me know which version of Jenkins you are using.

**Comment by OlgaMaciaszek** [comment]
@pskumar448 1.633

**Comment by pskumar448** [comment]
@OlgaMaciaszek 
Verified the Issue2 in Jenkins version 1.642.1 and it is working fine. 
Actually before when verifying I have Jenkins version 1.565

@tommysdk 
What is the baseline version of Jenkins required for DPP.

**Comment by tommysdk** [comment]
@pskumar448: the required version is stated in the pom.xml

**Comment by pskumar448** [comment]
@tommysdk 
In the pom.xml file it is Jenkins version 1.565
Issue2 is persists in Jenkins version 1.565 and not there in 1.633 and above.
Here what is the consideration whether to fix the issue for older Jenkins users or can we make this as open issue as the users will be less in count.

@OlgaMaciaszek 
Could you able to fix this issue for the Jenkins version 1.565

**Comment by OlgaMaciaszek** [comment]
@pskumar448 @tommysdk 
I have retested it on Jenkins 1.565 and I can't reproduce the bug either. Please find attached the screenshot from the view made with jobs provided by @pskumar448, with excluded steps.
So I suggest to merge it and if there are really some users that use Jenkins 1.5 with the exclude jobs feature and report this issue to us, then I could get back to it. Btw., 1.5 seems like a pretty outdated release now. We have already switched to Jenkins 2 :).
jenkins-1_5

**Comment by OlgaMaciaszek** [comment]
@tommysdk how do we stand with this PR? Do you think it could be merged? If not, what should be fixed/ modified for it to be considered. If we manage to merge it, we will be able to go back to using upstream :) in place of our fork, so it's quite important for us.

**Comment by tommysdk** [comment]
@OlgaMaciaszek Let me try this out during this week. Although this branch now has conflicts with current master as I merged some new features yesterday. Could you possibly rebase with current master?

The main concerns regarding hiding jobs in pipelines are those already stated in the https://issues.jenkins-ci.org/browse/JENKINS-26210 issue. Although we have had several requests for a feature similar to this (solved in one way or another) so it would obviously be nice to be able to accomodate a need for it in the community.

Do you have any suggestions for how to visualize that jobs are hidden? It is probably not trivial to display if a hidden job fails in the current UI. Would it be possible to display a text, e.g. at the top that pipeline contains jobs hidden from the view in some way? We are open to suggestions.

**Comment by tommysdk** [comment]
@OlgaMaciaszek I've tested the change set briefly but for me, the regular expression does not seem to take effect as expected. I believe I resolved the conflicts properly. It would be nice if you could do the same and verify the behaviour with current master.

I agree with @pskumar448 that it would be preferrable to have the regex validation in the configuration view instead of just showing the "Error communicating to server! Internal Server Error" when rendering the view. Like Jenkins does for e.g. downstream dependency job configurations when specifying non-existing jobs. It might be that it is not possible with the current code in the DPP. It would be nice to support that though but I assume that could require some quite big changes.

**Comment by patbos** [comment]
My suggested solution for https://issues.jenkins-ci.org/browse/JENKINS-26210 would be to add a "hide this job" option to the PipelineProperty.

**Comment by tommysdk** [comment]
I've re-tested this solution after 250a00e71a509bedceec158e57e382810f967848 and I cannot see the regular expression take effect on various pipelines I tested with.

I'm not convinced that a regular expression is the best and most user friendly way to configure this behaviour.

**Comment by OlgaMaciaszek** [comment]
@tommysdk Could you give the examples of pipelines where it didn't work?

**Comment by pskumar448** [comment]
@OlgaMaciaszek 
Along with Regex to hide the Jobs in Pipeline view, try to give option in Job property whether to hide this Job in pipeline or not. And also provide option to override that in config screen show or hide hidden jobs.

**Comment by tommysdk** [comment]
If there is no further adjustments intended for this feature according to the discussions above we will probably close this PR in the near future.

**Comment by tommysdk** [comment]
Closing stale pull request.

**Pull request closed without merging**
