### PR TITLE
JENKINS-43024 Improved pagination usability by showing pagination top and bottom

### PR DESCRIPTION
**Pull request by pskumar448**

### CODE REVIEW

**Comment by tommysdk** [comment]
@pskumar448 thank you for the pull request! I'll take a look as soon as possible

**Comment by tommysdk** [comment]
A few thoughts:
* If pagination is enabled and all data is contained within one page (no need for additional pages), it would be nice to hide the sole 1 paging page. We could show the pagination if 2 or more pages are necessary
* Could we add a little bit of extra space below the pagination on top (preferably the same amount as above)? See picture below:
image

We should probably add support for pagination for views configured for Jenkins pipeline as well, but I think we should address that in a separate issue.

**Comment by pskumar448** [comment]
Ok. Sure I will add the space to bottom as top.
When single page hiding the pagination, yes will hide it and let you know once done.

**Comment by pskumar448** [comment]
Done with the review items. Added space after the pagination and not showing the pagination when total no. of pipelines are less than the page size.

**Comment by tommysdk** [comment]
@pskumar448 Great job! Thanks for yet another contribution to the Delivery Pipeline plugin! Keep it up!

**Pull request merged**
