### PR TITLE
JENKINS-39856 fixed memory leak caused by jsplumb

### PR DESCRIPTION
**Pull request by bobo**
Fixed a memory leaked caused by how jsplumb was initiated.

### CODE REVIEW

**Comment by patbos** [comment]
Great

**Comment by tommysdk** [comment]
Running this version for a day on a Jenkins instance with several pipelines to see if the issue is addressed.

**Comment by tommysdk** [comment]
Thank you @bobo for yet another contribution!

**Comment by pskumar448** [comment]
@bobo @tommysdk 
Let me know whether we can have a jsPlumb instance for each component instead of one instance for all components.
The reason for asking with the single instance of jsPlumb for a page, it has shown impact on the having multiple Delivery Pipeline Dashboard Portlet.
I am working on this, but with out creating instance atleast for each component, the repaint is occurring continuously and arrows are not coming up.

Let me know your thoughts

-Suresh

**Comment by tommysdk** [comment]
@pskumar448 would it be possible to create a reproducing test case for your scenario? So that we can avoid these unwanted consequences in the future. The memory leak addressed was quite severe when running full screen view with multiple pipelines for a longer period of time (e.g. on an information radiator). If you would be able to address both of these concerns in a proposal, that would be great!

**Comment by pskumar448** [comment]
@tommysdk 
Yes we also faced same issue in normal view too, page crashes after some time. 
I am working to fix the issue, which can resolve both scenarios.

**Comment by tommysdk** [comment]
@pskumar448 great to hear! Just open a new ticket for it and we'll take it from there!

**Comment by tommysdk** [comment]
@pskumar448 just noticed your separate PR now, let's continue the discussion there!

**Pull request merged**
