### PR TITLE
[JENKINS-31317] shows multiple stages per row in the delivery pipeline

### PR DESCRIPTION
**Pull request by michael-chen-at-lab49**
Please refer to https://issues.jenkins-ci.org/browse/JENKINS-31317

### CODE REVIEW

**Comment by patbos** [comment]
Thanks for the PR, will test this as soon as possible

**Comment by michael-chen-at-lab49** [comment]
Hi Patrik,

Please let me know when this PR could be incorporated into the plugin.

If other changes are needed for it to make it to the plugin, please let me
know and I'll get it done.

Thanks much.

-Michael

On Thu, Nov 19, 2015 at 2:52 PM, Patrik Boström <notifications@github.com>
wrote:

> Thanks for the PR, will test this as soon as possible
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Diabol/delivery-pipeline-plugin/pull/163#issuecomment-158175158>
> .
>

-- 
 

This email and any attachments may contain information which is 
confidential and/or privileged. The information is intended exclusively for 
the addressee and the views expressed may not be official policy, but the 
personal views of the originator. If you are not the intended recipient, be 
aware that any disclosure, copying, distribution or use of the contents is 
prohibited. If you have received this email and any file transmitted with 
it in error, please notify the sender by telephone or return email 
immediately and delete the material from your computer. Internet 
communications are not secure and Lab49 is not responsible for their abuse 
by third parties, nor for any alteration or corruption in transmission, nor 
for any damage or loss caused by any virus or other defect. Lab49 accepts 
no liability or responsibility arising out of or in any way connected to 
this email.

**Comment by patbos** [comment]
Hi,
Sorry taking so long, now I have tested the changes and it works great. 
Will merge this now. Thanks for your contribution!

**Comment by michael-chen-at-lab49** [comment]
Thanks much!

How soon will this change get rolled into a release?

Sent from my phone

> On Dec 4, 2015, at 09:58, Patrik Boström <notifications@github.com> wrote:
> 
> Hi,
> Sorry taking so long, now I have tested the changes and it works great. 
> Will merge this now. Thanks for your contribution!
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 
 

This email and any attachments may contain information which is 
confidential and/or privileged. The information is intended exclusively for 
the addressee and the views expressed may not be official policy, but the 
personal views of the originator. If you are not the intended recipient, be 
aware that any disclosure, copying, distribution or use of the contents is 
prohibited. If you have received this email and any file transmitted with 
it in error, please notify the sender by telephone or return email 
immediately and delete the material from your computer. Internet 
communications are not secure and Lab49 is not responsible for their abuse 
by third parties, nor for any alteration or corruption in transmission, nor 
for any damage or loss caused by any virus or other defect. Lab49 accepts 
no liability or responsibility arising out of or in any way connected to 
this email.

**Comment by patbos** [comment]
Released now.

**Pull request merged**
