### PR TITLE
JENKINS-33175 Fix for Firefox and IE, the arrow lines move when scrolling the page, breaking the connections

### PR DESCRIPTION
**Pull request by pskumar448**
Fix for Firefox and IE, the arrow lines move when scrolling the page, breaking the connections

Before in Firefox browser
before-firefox

After fix in Firefox browser
after-firefox

Before in IE browser
before-ie

After fix in IE browser
after-ie

### CODE REVIEW

**Comment by dawidmalina** [comment]
Wowo we need this :+1:

**Comment by tommysdk** [comment]
Awesome! We really need to fix this issue. I'll take a look at it in the beginning of next week.

**Comment by patbos** [comment]
Great!

**Comment by tommysdk** [comment]
Fix verified on both IE and Firefox.

**Comment by tommysdk** [comment]
Merged to master.

Thank you for the fix @pskumar448 !

**Pull request merged**
