### PR TITLE
[JENKINS-19121] Expose isParameterized on task to help running non-first job manually

### PR DESCRIPTION
**Pull request by eddiesholl**
Parameterized manual triggering is straight forward on the first job in a pipeline, as it uses a simple redirect. I have used this approach for downstream manual triggering as well, instead of the current post, which can't seek user feedback and input on triggering.

### CODE REVIEW

**Comment by sirlatrom** [comment]
@eddiesholl Thank you for bothering to make this! I've been wanting something like this for ages.

However, build parameters from the upstream job do not carry over to the `$JENKINS/job/$JOB/build` parameter input form on the downstream job that this PR redirects to.

An option might be to check if the ["Build With Parameters" plugin](https://wiki.jenkins-ci.org/display/JENKINS/Build+With+Parameters+Plugin) is installed, and (optionally?) only enable the redirect in that case. If it is installed, the parameter values can be passed to the `$JENKINS/job/$JOB/parambuild` page with a query parameter for each filled out parameter from the previous job. The parameter values would be computed the same way as they are currently when triggering a new build directly from the pipeline (e.g. when the manual step has a parameter option of "Current build parameters").

**Comment by eddiesholl** [comment]
Yes I can see how the solution you've proposed would be better. My current scenario that triggered this effort doesn't require any parameters, so would be made possible with this partial solution. I've got a job to bump the version number on an npm package, it's all pure user input.

I'd propose a second issue is raised for not supporting parameters (there's probably already one specifically about manual with params), so at least some scenarios/users can receive this fix.

I would understand though if it is deemed necessary to go 'all or nothing', and get the parameters passed as well.

**Comment by tommysdk** [comment]
@eddiesholl is it possible for you to rebase this with current master as it seems like this branch has become outdated (and therefore having conflicts)?

**Comment by eddiesholl** [comment]
OK should be good to go now

**Comment by tommysdk** [comment]
@eddiesholl Sorry for not getting back to you on this one. Will try to go through this and the other pull requests as soon as possible.

**Comment by tommysdk** [comment]
Could we add a test case for this feature? Would be desirable for catching possible regression issues in the future.

**Comment by tommysdk** [comment]
@eddiesholl I agree with @sirlatrom that I think we should address all known cases when introducing this feature, instead of having a partial solution in place. Do you have the ability to contribute those changes to this feature request as well?

**Comment by eddiesholl** [comment]
It's unlikely to be honest, i'm completely n00b status when it comes to developing in the jenkins plugin space, and don't think I will find the time to dive much deeper here.

**Comment by tommysdk** [comment]
Closing this as the proposed solution is deemed unsufficient according to the above discussions. If anyone is interested to pick up this feature again we can open it again.

**Comment by tommysdk** [comment]
For future reference: The specified issue JENKINS-19121 is referencing an issue in the build-pipeline-plugin. Any work on the Delivery Pipeline plugin (DPP) should have an associated DPP specific issue.

**Pull request closed without merging**
