### PR TITLE
Show promotions and description on the pipeline

### PR DESCRIPTION
**Pull request by abnath**
Show promotions and description on the pipeline. Both are configurable(on/off) via config page.

### CODE REVIEW

**Comment by dawidmalina** [comment]
This is prabably continuation of this https://github.com/Diabol/delivery-pipeline-plugin/pull/113. @patbos when you can merge this?

**Comment by patbos** [comment]
Got this errors every second build when i build master branch:
Tests run: 7, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 6.789 sec <<< FAILURE! - in se.diabol.jenkins.pipeline.domain.TaskTest
testGetAg(se.diabol.jenkins.pipeline.domain.TaskTest)  Time elapsed: 0.943 sec  <<< ERROR!
java.lang.NullPointerException: null
	at se.diabol.jenkins.pipeline.domain.status.SimpleStatus.isBuildPromoted(SimpleStatus.java:193)
	at se.diabol.jenkins.pipeline.domain.status.SimpleStatus.getStatusFromResult(SimpleStatus.java:176)
	at se.diabol.jenkins.pipeline.domain.status.SimpleStatus.resolveStatus(SimpleStatus.java:167)
	at se.diabol.jenkins.pipeline.domain.Task.getAggregatedTask(Task.java:199)
	at se.diabol.jenkins.pipeline.domain.TaskTest.testGetAg(TaskTest.java:78)

testFailedThenQueued(se.diabol.jenkins.pipeline.domain.TaskTest)  Time elapsed: 0.526 sec  <<< ERROR!
java.lang.NullPointerException: null
	at se.diabol.jenkins.pipeline.domain.status.SimpleStatus.isBuildPromoted(SimpleStatus.java:193)
	at se.diabol.jenkins.pipeline.domain.status.SimpleStatus.getStatusFromResult(SimpleStatus.java:179)
	at se.diabol.jenkins.pipeline.domain.status.SimpleStatus.resolveStatus(SimpleStatus.java:167)
	at se.diabol.jenkins.pipeline.domain.Task.getLatestTask(Task.java:176)
	at se.diabol.jenkins.pipeline.domain.TaskTest.testFailedThenQueued(TaskTest.java:164)

testIsRebuildableNoPermission(se.diabol.jenkins.pipeline.domain.TaskTest)  Time elapsed: 1.79 sec  <<< ERROR!
java.lang.NullPointerException: null
	at se.diabol.jenkins.pipeline.domain.status.SimpleStatus.isBuildPromoted(SimpleStatus.java:193)
	at se.diabol.jenkins.pipeline.domain.status.SimpleStatus.getStatusFromResult(SimpleStatus.java:179)
	at se.diabol.jenkins.pipeline.domain.status.SimpleStatus.resolveStatus(SimpleStatus.java:167)
	at se.diabol.jenkins.pipeline.domain.Task.getLatestTask(Task.java:176)
	at se.diabol.jenkins.pipeline.domain.TaskTest.testIsRebuildableNoPermission(TaskTest.java:215)

testIsRebuildable(se.diabol.jenkins.pipeline.domain.TaskTest)  Time elapsed: 1.1 sec  <<< ERROR!
java.lang.NullPointerException: null
	at se.diabol.jenkins.pipeline.domain.status.SimpleStatus.isBuildPromoted(SimpleStatus.java:193)
	at se.diabol.jenkins.pipeline.domain.status.SimpleStatus.getStatusFromResult(SimpleStatus.java:179)
	at se.diabol.jenkins.pipeline.domain.status.SimpleStatus.resolveStatus(SimpleStatus.java:167)
	at se.diabol.jenkins.pipeline.domain.Task.getLatestTask(Task.java:176)
	at se.diabol.jenkins.pipeline.domain.TaskTest.testIsRebuildable(TaskTest.java:184)

**Comment by cooolmagic** [comment]
@patbos Not sure how these tests where passing before. Looks like they are not mocking their dependencies and are accessing shared states (in static fields). For now I have added null checks and tests are now passing for me. See PR 125.

**Comment by cooolmagic** [comment]
@patbos @dawidmalina Do you know when is the next plugin release will be?

**Pull request merged**
