### PR TITLE
Added date filters to retrieve historical pipelines

### PR DESCRIPTION
**Pull request by pskumar448**
To navigate through the historical pipelines i.e last quarter or last year with pagination also its tough to navigate and cannot narrow the pipelines.

Added date filters to narrow down the pipelines.

image

### CODE REVIEW

**Comment by pskumar448** [comment]
@tommysdk 
Any thoughts on this feature.

**Comment by mrfatstrat** [comment]
Hi @pskumar448 and thank you for your contribution we appreciate it!  For this PR I'm a bit skeptic and I'm wondering why you would need to browse pipelines that are many months old? I can see how it can be useful but, don't get me wrong, I am not sure this functionality to the pipeline view. The primary intention with DPP is displaying the current state and progress in a dashboard friendly way. Browsing old builds and filter on several month old data in this view I think is a rare use case. Also, keeping old builds in Jenkins too long is an anti-pattern that degrades performance so we don't want to encourage that. If you need to keep old builds, e.g. for audit purposes, I always recommend using another tool like ELK or Splunk that is more suited for that kind of use case.

**Comment by pskumar448** [comment]
Hi @mrfatstrat
Thanks for sharing your thoughts.
If we transferred the data to some other tool like ELK or Splunk (for this again we need to have extra hardware and use cases to browse old history), we are loosing the view of the pipeline (Starting to End Stage wise, total build time and other information providing by DPP). Why we browse to old pipelines to give report on the development progress. Our case is like this, we give access to only to DPP view to the Projects team to look at the progress or any issues. Project lead wants to see from when Unit Tests are failing, then he needs to browse the old pipelines (mostly dev people are not aware of Jenkins navigation and digging information). 

This feature only visible in normal view when enabled, in full screen view this filter option won't visible. Just this an add-on to the DPP as an feature.

**Comment by tommysdk** [comment]
@pskumar448 thank you for your proposal!

Regarding this feature, I agree with @mrfatstrat. Although I understand the reasoning behind the proposal, I do not think it is the purpose of this plugin to support that use case. Maybe a feature which could support a use case of this sort would be to be able to generate some kind of report to model a specific pipeline run after it has finished.

**Comment by pskumar448** [comment]
OK.

**Pull request closed without merging**
