### PR TITLE
JENKINS-29133 - 'Enable start of new pipeline build' does not work with parameterized trigger

### PR DESCRIPTION
**Pull request by dawidmalina**

### CODE REVIEW

**Comment by dawidmalina** [comment]
Looks like test coverage stucked.

**Comment by patbos** [comment]
@dawidmalina No problem, it might take up to several hours before the coverage from Coveralls to be reported.

**Comment by dawidmalina** [comment]
@patbos What do you think about this change?

**Comment by patbos** [comment]
Great job! Would be nice to have a integration test of it since it is hard to cover by unit test.

**Comment by dawidmalina** [comment]
@patbos - done

**Comment by patbos** [comment]
Great work!

**Pull request merged**
