### PR TITLE
JENKINS-45213 - Improve overview theme

### PR DESCRIPTION
**Pull request by bstream**
* Replace overall tabular layout with normal divs and spans.
* Move several inline styles to css.
* Make overall style more compact.

JENKINS-45213: https://issues.jenkins-ci.org/browse/JENKINS-45213

### CODE REVIEW

**Comment by tommysdk** [comment]
Thank you @bstream for the contribution and effort to clean up the stylesheets while improving on the overview theme! I just reviewed the pull request and I only find one small issue in aggregated views while using Firefox.

In Safari, the version number of each stage is properly shown as expected in the stage title bar, such as: 
image

In Firefox however, the version number is instead displayed next to the task name:
image

Same issue occurs both in normal view and in full screen view. Tested with Firefox 54.0.1 (64-bit) and Safari 10.1.1 (11603.2.5).

If you would be able to address the mentioned issue, I think it would be good to merge!

**Comment by bstream** [comment]
@tommysdk Thanks for the thorough check! The issue that you saw in firefox should now be fixed :)

**Comment by tommysdk** [comment]
@bstream Great! Thanks for the quick response, I will take a new look!

**Comment by tommysdk** [comment]
@bstream Looks good! Just waiting for the CI build to finish successfully, then I'll merge the code changes.

**Comment by pskumar448** [comment]
Thanks to clean up and improving overview theme, I thought so many times but didn't get time.
Great job by improving my bad code. Thanks...

**Pull request merged**
