### PR TITLE
Updated CSS styles for Overview theme fixing large fonts

### PR DESCRIPTION
**Pull request by pskumar448**

### CODE REVIEW

**Comment by pskumar448** [comment]
@dawidmalina @tommysdk 
Fonts of the description table reduced and made equally with the Stage headers.

dppoverview

**Comment by tommysdk** [comment]
Example of misaligned cell height in full screen view:
dpp_overview

**Comment by pskumar448** [comment]
@tommysdk 
Misalignment in full screen view issue fixed.

-Suresh

**Comment by tommysdk** [comment]
Amended commit message and merged to master: f95a9f89655f2b35ef705b506457742b747817f8

Thank you @pskumar448 for your addressing the feedback quickly!

**Pull request closed without merging**
