### PR TITLE
JENKINS-60658

### PR DESCRIPTION
**Pull request by dfoulkes**
include the missing dependency with the latest version of the Joda TimeDate

### CODE REVIEW

**Comment by dfoulkes** [comment]
FYI there’s been a bug in the Travis file for months

**Comment by cm0s** [comment]
Any idea when this pull request is going to be merged? I really need this correction

**Comment by dfoulkes** [comment]
@cm0s I gave up waiting, the fork for the plugin with my change can be found at: https://github.com/dfoulkes/delivery-pipeline-plugin

**Comment by cm0s** [comment]
@patbos Thank you for the merge. Do you think it could be possible to release a 1.4.1 version for this fix?

**Pull request merged**
