### PR TITLE
Improved JS codestyle according to best practices

### PR DESCRIPTION
**Pull request by Crasher-ua**
Each step of this change will makes code a little bit more consistent, changes difference
will have less size and logical problems could be revealed easier.

Commit 1: variables declaration
Commit 2: indentation

Next steps will be performed in the scope of other pull requests. In further request I want to reduce overall complexity of JS code and find logical problems if they are available.

### CODE REVIEW

**Comment by tommysdk** [comment]
Hi @Crasher-ua! Thank you for the proposed codestyle changes! Will take a look as soon as possible and provide some feedback.

**Comment by Crasher-ua** [comment]
Hello @tommysdk! Thanks a lot for review. Sure, I've added this file to pull request too.

**Comment by tommysdk** [comment]
Thank you very much @Crasher-ua for your quick response and additions to the pull request! The change set looks good.

**Comment by tommysdk** [comment]
Thank you @Crasher-ua for your contribution!

**Pull request merged**
