### PR TITLE
[JENKINS-39041] Implemented new visualization for the description of every pipeline

### PR DESCRIPTION
**Pull request by pskumar448**
@tommysdk 
Got an idea after seeing the pipeline stage view, we also can represent the pipeline description data in the manner of dashboard for quick grasping.
Below is the screenshot how it look after running with this change.
Let me know your thoughts.

dppnewlook

dppnewlookfs

Thanks,
Suresh

### CODE REVIEW

**Comment by pskumar448** [comment]
@tommysdk 
Let me know feedback and thoughts on this new visualization, based on review points will work further to touch all screens.

**Comment by pskumar448** [comment]
I think maintainers are busy, ping me back when got time to review this PR.

**Comment by patbos** [comment]
Thanks for the PR, the result looks awesome! Would be cool to support different styles/themes in a smooth way. Is it possible to change the pipe.js and add this new style as a theme in some way?

**Comment by pskumar448** [comment]
Thanks @patbos for feedback.
Yes we can enable a option to end user select different styles from the drop-down. This can be same like themes how we have at present.

**Comment by pskumar448** [comment]
@patbos 
Could you please help me in naming this theme. So that I can create a theme for the above visualization.

**Comment by pskumar448** [comment]
Added as new theme named "specto". Let me know your inputs regarding this theme.

**Comment by tommysdk** [comment]
Great job @pskumar448! It looks awesome! We'll take a look at it as soon as possible!

**Comment by pskumar448** [comment]
@tommysdk 
Any feedback on this.

**Comment by pskumar448** [comment]
@tommysdk 
Any update on this.

**Comment by tommysdk** [comment]
@pskumar448 I'm sorry I have been choked with other things lately and haven't been able to find time to look at this I'm afraid. 

@patbos @mrfatstrat @rickard-von-essen @marcusphi @jesperps @hakan-ronngren anyone of you who are able to look at this proposed feature?

**Comment by tommysdk** [comment]
@pskumar448 do you have any thoughts regarding my comments above?

**Comment by tommysdk** [comment]
Also noticing that this PR now has a conflict with the updated pipe.js on master

**Comment by pskumar448** [comment]
@tommysdk 
Yes, going through your inputs and will update once I finished.

**Comment by tommysdk** [comment]
@pskumar448 thanks for keeping me updated! Planning to release a new version soon and it would definitely be great if this feature could be part of it.

**Comment by pskumar448** [comment]
@tommysdk 
Rebased with current master. And given the name of the theme as "Overview". JIRA ticket raised for the same and find the Url from below https://issues.jenkins-ci.org/browse/JENKINS-39041 
Let me know your feedback.

-Suresh

**Comment by tommysdk** [comment]
I've reviewed this feature request and it looks good so I'll merge this. Thank you @pskumar448 for this new theme!

**Comment by dawidmalina** [comment]
I've checked this change (current master) and it looks very nice but in my case fonts are just too big.
zrzut ekranu 2016-10-21 o 12 23 29

Headers and internal text should be exactly the same as for stages.

**Comment by tommysdk** [comment]
@dawidmalina Thank you for your feedback! That is a reasonable observation. @pskumar448 Could you consider updating the stylesheet according to Dawid's suggestion?

**Comment by pskumar448** [comment]
@dawidmalina @tommysdk 
Ok. I will work on the CSS part and will update once I finish.

**Comment by tommysdk** [comment]
@pskumar448 great stuff!

**Pull request merged**
