### PR TITLE
Fix JENKINS-33594: Rebuilding broken in Jenkins ver. 1.653

### PR DESCRIPTION
**Pull request by noidi**
The cause list is immutable as described in the comments of
[JENKINS-33467](https://issues.jenkins-ci.org/browse/JENKINS-33467).

### CODE REVIEW

**Comment by martino-jelli** [comment]
Any idea on when this new code will be released?
Thanks to all for your help!

**Comment by noidi** [comment]
@martino-jelli, in case you can't wait for the fix to be merged, I've uploaded a binary built from my branch: https://www.dropbox.com/s/t4aj3l3n6ea0qau/delivery-pipeline-plugin.hpi?dl=0

**Comment by martino-jelli** [comment]
@noidi Thanks for sharing it!

**Comment by martino-jelli** [comment]
@noidi I tryed your fix, but the manual step is still not updated! Thanks anyway

**Comment by noidi** [comment]
@martino-jelli Did you create a new instance of the pipeline by starting a new build of the first job? I think that all jobs must be run with the fixed version or the chain of causes to the first job will be broken.

**Comment by martino-jelli** [comment]
@noidi Yes, a new commit started the pipeline and I have a manual step to deploy it to prod, which is not updated and still shown an older version.

**Comment by noidi** [comment]
@martino-jelli I just noticed that your problem is with manual steps and not rebuilding. This patch (to Delivery Pipeline Plugin) fixes rebuilding. The bug with manual steps is in Build Pipeline Plugin (see [JENKINS-33591](https://issues.jenkins-ci.org/browse/JENKINS-33591)) and is hopefully fixed by my pull request there. The patched version of Build Pipeline Plugin is available for testing here: https://www.dropbox.com/s/9ywjl8trtudatq6/build-pipeline-plugin.hpi?dl=0.

**Comment by martino-jelli** [comment]
@noidi Thanks you so much for your help, the patched version of Build pipeline fixed the issue!
Cheers

**Comment by tommysdk** [comment]
Code change verified. Thank you for your contribution!

**Pull request merged**
