### PR TITLE
Show promotions and description on the pipeline

### PR DESCRIPTION
**Pull request by cooolmagic**
Show promotions and description on the pipeline. Both are configurable(on/off) via config page.

### CODE REVIEW

**Comment by cooolmagic** [comment]
Few more details about show descriptions:
- User can configure view to show job descriptions on the pipeline

About show promotions:
- User can configure view to show job promotions on the pipeline
- It will show all promotions in descending order of start time
- It will show promotion badge, title, duration and user

Here are few screenshots:

image
image

**Comment by cooolmagic** [comment]
Here is how we are using these features in our enterprise pipeline. This one heavily uses description feature.

untitled

**Comment by dawidmalina** [comment]
Looks promising. Is it possible to make test coverage happy?

**Comment by tommysdk** [comment]
Really nice feature! Good job! I've been missing the ability to have the test stats (tests run, failed, skipped) easily accessible from the pipeline view.

Is there a JIRA ticket for this issue? If not, please create one so we can keep track of all changes going into the plugin.

Could you please take a look if you can raise the test coverage?

**Comment by abnath** [comment]
Ah.. I want to. But some of promotion plugin classes are final and cannot be mocked by Mockito. And I would hate to introduce PowerPock or something similar. Thoughts?

**Comment by cooolmagic** [comment]
Ah.. I want to. But some of promotion plugin classes are final and cannot be mocked by Mockito. And I would hate to introduce PowerPock or something similar. Thoughts?

**Comment by cooolmagic** [comment]
Ok. I have improvised a little and added some more coverage. See if this is acceptable?

**Comment by tommysdk** [comment]
We'll take a look at it as soon as possible, thanks!

**Comment by patbos** [comment]
Thanks for the PR! Looks good. I have one issue. Promoted Build Plugin is an optional dependency. But in the code added in this PR uses classes in the Promoted Build Plugin directly. This will make Promoted Build Plugin dependency mandatory. I would prefer to still have the dependency to Promoted Build Plugin optional.

**Comment by dawidmalina** [comment]
Any update for this PR. @patbos maybe you can propose @cooolmagic howto deal with your requirement about dependency.

**Comment by cooolmagic** [comment]
I have made the changes to make promotion status as optional extension. Please take a look.

**Comment by patbos** [comment]
Looks good! I will do some local testing and come back.

**Comment by patbos** [comment]
@cooolmagic Have done some testing now and the optional extension work!
Cant merge the PR now since it has a couple of conflicts. Please merge from master and squash the commits.

**Comment by dawidmalina** [comment]
@cooolmagic looks like you forgot to finish junit test part. Changes in TestResult and Task are ready but you prabably missed changes on DeliveryPipelineView and pipe.js.

**Comment by cooolmagic** [comment]
@dawidmalina JENKINS-22843 looks like a new feature request. I took the latest 0.9.5 and everything is working as expected.

**Comment by dawidmalina** [comment]
@cooolmagic I don't see option to show TestResult from Task. There were 2 new properties:
    private boolean showDescription = false;
    private boolean showPromotions = false;

There is no option to show TestResult on view configuration page. See https://github.com/Diabol/delivery-pipeline-plugin/blob/master/src/main/java/se/diabol/jenkins/pipeline/DeliveryPipelineView.java

Same for https://github.com/Diabol/delivery-pipeline-plugin/blob/master/src/main/webapp/pipe.js I don't see section like on your screens (Tests run x, Failures x, Skipped x).

So if this part will be compleated it will somehow cover JENKINS-22843.

**Comment by tommysdk** [comment]
What is the JIRA ticket associated with this particular PR?

**Comment by cooolmagic** [comment]
@dawidmalina Ahh.. those test results in screenshot are set via description. We have a post build groovy script that parses console logs and set test results in description which are the reflected on the pipeline. I believe hudson has no direct API for test results. But there are indirect ways via optional 'aggregate junit reports' plugin. I will explore more.

**Pull request closed without merging**
