### PR TITLE
Ability to hide tasks in stages from pipeline view using Delivery Pip…

### PR DESCRIPTION
**Pull request by pskumar448**
When configuring upstream and downstream jobs, required some jobs to create which are going to handle certain background functionality which are not required in pipeline to visible.

This will work best with when we configure Stages and Tasks. Provided check box to every Job configuration of Delivery Pipeline Configuration whether to show/hide in pipeline.

Example:
**View Before**
before

**View After**
after

### CODE REVIEW

**Comment by pskumar448** [comment]
This fixes the Issue 
https://issues.jenkins-ci.org/browse/JENKINS-26210

**Comment by pskumar448** [comment]
Hey @patbos 
Could you verify this and let me know.
1) Provided option in Job configuration whether to Hide this in Stage Tasks.
2) In Delivery Pipeline given an option for viewing the hidden tasks with out modifying the Job's configuration.

This is very small modification see if this can fit.
Travis-CI failed because of unstable. Could you re-trigger the checks.

**Comment by tommysdk** [comment]
Hi! Thank you for your PR! I haven't had time to try out the solution yet. If you have a pipeline A -> B -> C and hide B only, and that job fails, how does it look in the UI then? I think it should be obvious in the visualization where the pipeline fails. The UI should be as straight-forward as possible.

**Comment by pskumar448** [comment]
Yeah I too agree with you UI should be straight-forward and clear. 
But I have a scenario like below.
A -> B -> C -> D
                       E
                       F
Job C doesn't have any business logic other than triggering Multi-Job Phase step kicks the Job D,E,F
In this case we don't need to Job C to be in pipeline of visualization. And also we are giving option in the view to override the Job configuration whether to show hidden tasks or not. 

Or else we have to consider if any hidden Job failed we have to show in pipeline, in other scenarios it can be hidden.

My view regarding the Delivery Pipeline is not just a UI, it became a dashboard in big screens. To keep minimal and providing more information what is happening and where we are the pipeline. With this motive I have taken up this requirement.

**Comment by tommysdk** [comment]
I agree with you, the DPP shines as an information radiator on big screens and I think it's a useful feature. Just thinking what should happen when a hidden job fails. It should be intuitive.

**Comment by pskumar448** [comment]
Ok @tommysdk 
Option 1) We can mark the Stage itself as failure if hidden Job failed.
Option 2) We can show the Job itself in pipeline marking it as Red, in other cases will hide.

Any other options let me know. Or else If any one option above is ok will move forward.

Thanks.

**Comment by tommysdk** [comment]
I'm really sorry for the slow feedback from us maintainers. For me it is currently really hard to find time at the moment. It is not an ideal situation. I'll see if anyone can give you some input on this feature.

**Comment by pskumar448** [comment]
Ok @tommysdk

**Comment by tommysdk** [comment]
Hi,
@pskumar448:
Thank you for your patience. I've now gone through your pull request and found the following problems.

If I enable delivery pipeline configuration for a job, omit stage and task name but mark the task as hidden, the job will still be visible in the pipeline.

If the stage and task names are present and the job is marked as hidden, the stage will still be shown even though no jobs for that stage are visible, which is ambiguous and looks weird.

I'm still not convinced about the feature in general as I don't find the visualisation intuitive, if jobs are hidden. I understand the use cases, but I'm afraid it will cause unnecessary confusion if a hidden job fails or if a hidden job has additional logic to it which should be considered from a pipeline point of view.

I suggest we continue the discussion in JIRA: https://issues.jenkins-ci.org/browse/JENKINS-26210

**Comment by pskumar448** [comment]
@tommysdk 
I fixed the above 2 problems.
We have to find a way how we can show if the hidden Job fails.

**Comment by tommysdk** [comment]
@pskumar448 Thank you for the updates. We'll have a look at it next week.

**Comment by pskumar448** [comment]
@tommysdk 
Ok I will wait for the feedback. :)

**Comment by tommysdk** [comment]
@pskumar448 Again, thank you for your patience. I'm sorry to inform that we have decided to reject this feature request. Please see https://issues.jenkins-ci.org/browse/JENKINS-26210 for further comments.

**Comment by pskumar448** [comment]
@tommysdk 
It's OK.

**Comment by pskumar448** [comment]
@tommysdk 
After going through the comments in another repo regarding this feature, but I have implemented same configuring at Job level to show or hide this project in DPP. And also given option to override the Job level configuration and displaying all the Stages & Tasks.

Don't know what happened at the time of submission this PR and rejected my PR.

**Pull request closed without merging**
