### PR TITLE
Allows users to adjust task display order in stage

### PR DESCRIPTION
**Pull request by seanly**
show task order by configure the order in build other (manual) .

### CODE REVIEW

**Comment by tommysdk** [comment]
@seanly Thank you for your contribution! Unfortunately some unit tests are failing with this code change, is that something you can look into as well?

I will take a deeper look at this request in the upcoming days and provide you some feedback.

**Comment by seanly** [comment]
OK，thank you . I re-thought and review the code.

**Comment by seanly** [comment]
@tommysdk add relationship resolver class to solve for "build other project( manual steps) " post build.

**Comment by tommysdk** [comment]
@seanly could you please elaborate a bit on the intent of the proposed code change and how it is intended to be used?

**Comment by seanly** [comment]
@tommysdk 

# The current situation
when jobA(deploy_qa_env) configure downstream jobs(update_db, update_transitsrv_code, update_logsrv_code), use manual trigger，the original diagram to display as follows:

deploy_qa_env job post build configure image: 
image

the current delivery pipeline show: 
image

**But the diagram I want to show is the sequence of tasks I configured（update_db, update_transitsvr_code, update_logsrv_code）**:

image


# Usage scenarios
We need to manually trigger when launched some steps and verification, the original way of showing here is using the job name, if we need to achieve the above shows the effect need to modify the job name, that will be very trouble.

If you have this pull request, you can easily adjust the display order

**Comment by tommysdk** [comment]
@seanly I see. Thank you for the explanation. Maybe we could add an option to select how to perform the sorting in such case. Unfortunately, I will not be able to look into this before the Christmas and New Year.

**Comment by tommysdk** [comment]
@seanly as this functionality will override core functionality in the plugin we will not merge this feature request as it could potentially break a lot of different use cases. Not certain either that the value of changing the behavior is of interest for the majority of users. For future proposals, any similar changes should be considered as optional configuration options.

**Comment by seanly** [comment]
I think of a way to, in their own plug-in implementation, this should also can achieve my goal, through inheritance. class : se.diabol.jenkins.pipeline.RelationshipResolver

**Pull request closed without merging**
